# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dictionaries
        run: |
          sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ bionic main'
          sudo apt update --allow-insecure-repositories
          sudo apt install dictd \
            dict \
            dict-de-en \
            dict-devil \
            dict-elements \
            dict-foldoc \
            dict-freedict-afr-deu \
            dict-freedict-afr-eng \
            dict-freedict-ara-eng \
            dict-freedict-bre-fra \
            dict-freedict-ces-eng \
            dict-freedict-ckb-kmr \
            dict-freedict-cym-eng \
            dict-freedict-dan-eng \
            dict-freedict-deu-bul \
            dict-freedict-deu-eng \
            dict-freedict-deu-fra \
            dict-freedict-deu-ita \
            dict-freedict-deu-kur \
            dict-freedict-deu-nld \
            dict-freedict-deu-pol \
            dict-freedict-deu-por \
            dict-freedict-deu-rus \
            dict-freedict-deu-spa \
            dict-freedict-deu-swe \
            dict-freedict-deu-tur \
            dict-freedict-eng-afr \
            dict-freedict-eng-ara \
            dict-freedict-eng-bul \
            dict-freedict-eng-ces \
            dict-freedict-eng-cym \
            dict-freedict-eng-deu \
            dict-freedict-eng-ell \
            dict-freedict-eng-fin \
            dict-freedict-eng-fra \
            dict-freedict-eng-gle \
            dict-freedict-eng-hin \
            dict-freedict-eng-hrv \
            dict-freedict-eng-hun \
            dict-freedict-eng-ita \
            dict-freedict-eng-jpn \
            dict-freedict-eng-lat \
            dict-freedict-eng-lit \
            dict-freedict-eng-nld \
            dict-freedict-eng-pol \
            dict-freedict-eng-por \
            dict-freedict-eng-rom \
            dict-freedict-eng-rus \
            dict-freedict-eng-spa \
            dict-freedict-eng-srp \
            dict-freedict-eng-swe \
            dict-freedict-eng-swh \
            dict-freedict-eng-tur \
            dict-freedict-epo-eng \
            dict-freedict-fin-bul \
            dict-freedict-fin-ell \
            dict-freedict-fin-eng \
            dict-freedict-fin-ita \
            dict-freedict-fin-jpn \
            dict-freedict-fin-nor \
            dict-freedict-fin-por \
            dict-freedict-fin-swe \
            dict-freedict-fra-bre \
            dict-freedict-fra-bul \
            dict-freedict-fra-deu \
            dict-freedict-fra-ell \
            dict-freedict-fra-eng \
            dict-freedict-fra-fin \
            dict-freedict-fra-ita \
            dict-freedict-fra-jpn \
            dict-freedict-fra-nld \
            dict-freedict-fra-pol \
            dict-freedict-fra-por \
            dict-freedict-fra-rus \
            dict-freedict-fra-spa \
            dict-freedict-fra-swe \
            dict-freedict-fra-tur \
            dict-freedict-gla-deu \
            dict-freedict-gle-eng \
            dict-freedict-gle-pol \
            dict-freedict-hrv-eng \
            dict-freedict-hun-eng \
            dict-freedict-isl-eng \
            dict-freedict-ita-deu \
            dict-freedict-ita-ell \
            dict-freedict-ita-eng \
            dict-freedict-ita-fin \
            dict-freedict-ita-jpn \
            dict-freedict-ita-pol \
            dict-gcide \
            dict-jargon \
            dict-moby-thesaurus \
            dict-wn
          cp /usr/share/dictd/*.dict.dz .
          cp /usr/share/dictd/*.index .
          cp /var/lib/dictd/db.list .
          
      - name: Commit changes
        run: |
          git add .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add some dictionaries"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
