# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dictionaries
        run: |
          sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ bionic main'
          sudo apt update --allow-insecure-repositories
          sudo apt install dictd \
            dict \
            dict-de-en \
            dict-devil \
            dict-elements \
            dict-foldoc \
            dict-freedict-cym-eng \
            dict-freedict-deu-eng \
            dict-freedict-eng-cym \
            dict-freedict-eng-deu \
            dict-freedict-eng-ell \
            dict-freedict-eng-fin \
            dict-freedict-eng-fra \
            dict-freedict-eng-hin \
            dict-freedict-eng-ita \
            dict-freedict-eng-jpn \
            dict-freedict-eng-lat \
            dict-freedict-eng-nld \
            dict-freedict-eng-pol \
            dict-freedict-eng-por \
            dict-freedict-eng-rom \
            dict-freedict-eng-rus \
            dict-freedict-eng-spa \
            dict-freedict-eng-swe \
            dict-freedict-epo-eng \
            dict-freedict-fra-eng \
            dict-freedict-ita-eng \
            dict-gcide \
            dict-jargon \
            dict-moby-thesaurus \
            dict-wn
          mkdir build
          cp /usr/share/dictd/*.dict.dz build/
          cp /usr/share/dictd/*.index build/
          cp /var/lib/dictd/db.list build/
          
      - name: Upload dictionaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
